# Generated by Django 4.0.4 on 2023-12-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adicionales',
            options={'ordering': ['nombre'], 'verbose_name': 'Adicional', 'verbose_name_plural': 'Adicionales'},
        ),
        migrations.AlterModelOptions(
            name='ingrediente',
            options={'ordering': ['nombre'], 'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredientes'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['nombre'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='torta',
            options={'ordering': ['nombre'], 'verbose_name': 'Torta', 'verbose_name_plural': 'Tortas'},
        ),
        migrations.AlterField(
            model_name='torta',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, null=True, related_name='tortas', to='venta.ingrediente'),
        ),
    ]
