# Generated by Django 4.0.4 on 2023-12-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_adicionales_options_alter_ingrediente_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adicionales',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='ingrediente',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='pedido',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='torta',
            unique_together={('nombre',)},
        ),
    ]
