# Generated by Django 4.0.4 on 2023-12-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_alter_adicionales_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torta',
            name='ingredientes',
            field=models.ManyToManyField(related_name='tortas', to='venta.ingrediente'),
        ),
    ]
