# Generated by Django 4.0.4 on 2023-12-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_alter_torta_ingredientes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adicionales',
            new_name='Adicional',
        ),
    ]
