# Generated by Django 4.0.4 on 2023-12-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_alter_pedido_options_alter_pedido_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='activo',
            field=models.IntegerField(choices=[(0, 'Pedida'), (1, 'Elaborada'), (2, 'Entregada'), (9, 'Cancelada')], default=0, verbose_name='Activo'),
        ),
    ]
