# Generated by Django 4.0.4 on 2025-05-06 00:37

import django.contrib.auth.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_alter_pedido_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Especial')], default=0, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='PrecioTortasIngredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especial', models.IntegerField(default=0, verbose_name='Especial')),
                ('normal', models.IntegerField(default=0, verbose_name='Normal')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Precio por ingrediente',
                'verbose_name_plural': 'Precios X ingrediente',
                'db_table': 'PreTorIngre',
                'ordering': ['especial', 'normal'],
                'unique_together': {('especial', 'normal')},
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
