# Generated by Django 4.0.4 on 2025-05-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_ingrediente_tipo_preciotortasingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='solicitud',
            field=models.JSONField(blank=True, null=True, verbose_name='Torta'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='donde',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Donde'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='picante',
            field=models.JSONField(blank=True, max_length=30, null=True, verbose_name='Picante'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='torta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Torta'),
        ),
    ]
