# Generated by Django 4.0.4 on 2025-05-08 00:13

import django.contrib.auth.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0010_pedido_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pagos',
                'ordering': ['-created'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='activo',
            field=models.IntegerField(choices=[(0, 'Pedida'), (1, 'Confirmado'), (2, 'Elaborada'), (3, 'Entregada'), (9, 'Cancelada'), (10, 'Cancelada entrega')], default=0, verbose_name='Activo'),
        ),
    ]
