# Generated by Django 4.0.4 on 2025-05-08 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0011_pagos_alter_pedido_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciotortasingredientes',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.pagos'),
        ),
    ]
