# Generated by Django 4.0.4 on 2025-05-08 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0012_preciotortasingredientes_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='adicionales',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='donde',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='picante',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='torta',
        ),
    ]
