# Generated by Django 4.0.4 on 2025-05-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0013_remove_pedido_adicionales_remove_pedido_donde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='cantidad_torta',
            field=models.IntegerField(default=1, verbose_name='Tortas'),
        ),
    ]
