# Generated by Django 4.0.4 on 2025-05-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0014_pagos_cantidad_torta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='importe_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Precio'),
        ),
    ]
