# Generated by Django 4.0.4 on 2025-05-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0016_remove_preciotortasingredientes_pago_pedido_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
    ]
