# Generated by Django 4.0.4 on 2025-05-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0017_llave'),
    ]

    operations = [
        migrations.AddField(
            model_name='llave',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
