# Generated by Django 4.0.4 on 2025-05-08 16:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0018_llave_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llave',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
