# Generated by Django 4.0.4 on 2025-05-08 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0019_alter_llave_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llave',
            options={'verbose_name': 'Tokens', 'verbose_name_plural': 'Token'},
        ),
        migrations.AlterField(
            model_name='llave',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='llave',
            unique_together={('token',)},
        ),
        migrations.AlterModelTable(
            name='llave',
            table='Llave',
        ),
    ]
